// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOCiS3ci-qfjjDnnYcS5Jo9_cAUpZvLeM',
    appId: '1:226178239332:web:e15215cad574cc5b64c871',
    messagingSenderId: '226178239332',
    projectId: 'chatapptute-e3c2d',
    authDomain: 'chatapptute-e3c2d.firebaseapp.com',
    storageBucket: 'chatapptute-e3c2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1JuYLQF33q3vucJLAdqXi5azC1S1r_s',
    appId: '1:226178239332:android:b5047bf025654e7864c871',
    messagingSenderId: '226178239332',
    projectId: 'chatapptute-e3c2d',
    storageBucket: 'chatapptute-e3c2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qAaCcKzqkX_Xr4SeSTEILsPu-3RvcSk',
    appId: '1:226178239332:ios:4b8c0fb27862ee3864c871',
    messagingSenderId: '226178239332',
    projectId: 'chatapptute-e3c2d',
    storageBucket: 'chatapptute-e3c2d.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6qAaCcKzqkX_Xr4SeSTEILsPu-3RvcSk',
    appId: '1:226178239332:ios:113affcf54f2451364c871',
    messagingSenderId: '226178239332',
    projectId: 'chatapptute-e3c2d',
    storageBucket: 'chatapptute-e3c2d.appspot.com',
    iosBundleId: 'com.example.minimalChatApp.RunnerTests',
  );
}
